application: ouarfc-vote
version: 2
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /static
  static_dir: static

- url: /favicon\.ico
  static_files: static/icons/favicon.ico
  upload: static/icons/favicon\.ico

- url: /browserconfig\.xml
  static_files: static/icons/browserconfig.xml
  upload: static/icons/browserconfig\.xml

- url: /worker.*
  script: src.worker.app
  login: admin

- url: /admin.*
  script: src.admin.app
  login: admin

- url: .*
  script: src.vote.app

builtins:
- remote_api: on

libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: latest

admin_console:
  pages:
    - name: View Results
      url: /results
